# Generated by Django 2.1.7 on 2019-06-11 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0014_problem_share_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.TextField(db_index=True)),
                ('title', models.TextField()),
                ('content', utils.models.RichTextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('on_class_practice', models.ManyToManyField(to='problem.Problem')),
            ],
            options={
                'db_table': 'course',
                'ordering': ('create_time',),
            },
        ),
    ]
