# Generated by Django 2.1.7 on 2019-06-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='on_class_practice',
            new_name='on_class_problems',
        ),
    ]
