# Generated by Django 2.1.7 on 2019-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_share_submission'),
        ('course', '0002_auto_20190612_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='after_class_problems',
            field=models.ManyToManyField(related_name='course_after_class_problems', to='problem.Problem'),
        ),
        migrations.AlterField(
            model_name='course',
            name='on_class_problems',
            field=models.ManyToManyField(related_name='course_on_class_problems', to='problem.Problem'),
        ),
    ]
