# Generated by Django 2.1.7 on 2019-06-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_powerpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerpoint',
            name='ppt',
            field=models.FileField(upload_to='course_ppt/'),
        ),
    ]
