# Generated by Django 2.1.7 on 2019-06-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20190617_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='on_class_problems',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_on_class_problems', to='problem.Problem'),
        ),
    ]
