# Generated by Django 2.1.7 on 2019-06-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20190617_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='display_id',
        ),
        migrations.AddField(
            model_name='course',
            name='charpter',
            field=models.TextField(default='初级班'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.TextField(default='第一节'),
            preserve_default=False,
        ),
    ]
