# Generated by Django 2.1.7 on 2019-06-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20190618_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerpoint',
            name='ppt',
            field=models.FileField(upload_to='ppt/'),
        ),
    ]
