# Generated by Django 2.1.7 on 2019-06-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_share_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
