# Generated by Django 2.1.7 on 2019-06-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0017_remove_file_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
