# Generated by Django 2.1.7 on 2019-06-14 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0018_delete_file'),
        ('video', '0002_auto_20190614_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionvideo',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
