# Generated by Django 2.1.7 on 2019-06-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_solutionvideo_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionvideo',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
