# Generated by Django 2.1.7 on 2019-06-14 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20190614_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionvideo',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
