# Generated by Django 2.1.7 on 2019-06-17 05:34

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20190614_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='solutionvideo',
            name='text_solution',
            field=utils.models.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solutionvideo',
            name='video_solution',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
