# Generated by Django 2.1.7 on 2019-06-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0018_delete_file'),
        ('video', '0008_auto_20190617_0534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolutionVideo',
            new_name='ProblemSolution',
        ),
    ]
