# Generated by Django 2.1.7 on 2019-06-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20190617_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsolution',
            name='video_solution',
            field=models.FileField(blank=True, null=True, upload_to='solution_video/'),
        ),
    ]
