# Generated by Django 2.1.7 on 2019-06-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20190617_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsolution',
            name='video_solution',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
