# Generated by Django 2.1.7 on 2019-06-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20190619_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemsolution',
            old_name='text_solution',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='problemsolution',
            old_name='video_solution',
            new_name='video',
        ),
    ]
