# Generated by Django 2.1.7 on 2019-06-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20190619_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsolution',
            name='video',
            field=models.TextField(default='default_video_name'),
            preserve_default=False,
        ),
    ]
